---
- hosts: localhost
  tasks:
  - name: create a VPC with dedicated tenancy and a couple of tags
    ec2_vpc_net:
      name: Group_task vpc
      cidr_block: 10.0.0.0/16
      region: us-east-1
      state: present