---
- name: Stop Services
  hosts: all #DB
  become: true
  become_method: sudo
  user: centos
  ignore_error: true     #Don't stop if there are errors
  tasks:
   - name: Stop r1soft on CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_vrsion == "7")
    systemd:
      name: sbm-agent
      state: stopped
    ignore_error: true

  - name: Stop r1soft on CentOS 6
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_vrsion == "6")
    systemd:
      name: cdp-agent
      state: stopped
    ignore_error: true

  - name: Stop Filebeat
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_vrsion == "7")
    systemd:
      name: filebeat
      state: stopped
    ignore_error: true


  - name: Stop NRPE
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_vrsion == "7")
    systemd:
      name: nrpe
      state: stopped
    ignore_error: true


  - name: Stop Mariadb
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_vrsion == "7")
    systemd:
      name: mariadb
      state: stopped
    ignore_error: true